version: '3'
services:
  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=fhir-datasource
    volumes:
      - ../dist:/var/lib/grafana/plugins/fhir-datasource
      - ./fhir-datasource.yml:/etc/grafana/provisioning/datasources/fhir.yml
    depends_on:
      - fhir
  fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    ports:
      - "8080:8080"
  loader:
    image: curlimages/curl:latest
    depends_on:
      - fhir
    volumes:
      - ../synthetic-data:/data
      - ../synthetic-data/load_data.sh:/load_data.sh
    entrypoint: ["/load_data.sh"]
